name: Build

on:
  push:
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:                                    # checks: write for Test Report
      contents: read
      actions: read
      checks: write
    steps:
      - name: Checkout code from repo
        uses: actions/checkout@v4.1.7

      - name: Set up JDK 17
        uses: actions/setup-java@v4.2.1
        with:
          distribution: 'corretto'
          java-version: 17
          cache: gradle

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3.5.0
        id: setup-gradle
        with:
            gradle-version: 8.8

      - name: Build with Gradle
        run: ./gradlew build

      - name: Test Report
        uses: dorny/test-reporter@v1.9.1
        if: success() || failure()                    # run this step even if previous step failed
        with:
          name: Junit Tests                           # Name of the check run which will be created
          path: build/test-results/test/TEST-*.xml    # Path to test results
          reporter: java-junit                        # Format of test results
